CREATE TABLE PASSENGER (
    PASSENGER_ID BIGINT PRIMARY KEY,
    SURVIVED BOOLEAN NOT NULL,
    PCLASS INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SEX VARCHAR(10) NOT NULL,
    AGE DOUBLE,
    SIB_SP INT NOT NULL,
    PARCH INT NOT NULL,
    TICKET VARCHAR(50) NOT NULL,
    FARE DOUBLE NOT NULL,
    CABIN VARCHAR(50),
    EMBARKED VARCHAR(10)
);
